assets/urls.py
from django.contrib import admin
from django.urls import path, include
from assets import views

app_name = "assets"
urlpatterns = [
    path('add/', views.add_view, name='asset_add'),
    path('ur/<int:ura_id>/add/', views.ura_to_asset_view, name='ura_asset_add'),
    path('list/', views.IndexView.as_view(), name='asset_list'),
    path('ur/list/', views.UrAView.as_view(), name='ur_asset_list'),
    path('<int:asset_id>/', views.asset_detail_view, name='asset_detail_view'),
    path('<int:asset_id>/update', views.asset_update_view, name='asset_update_view'),
    path('export/$', views.asset_export, name='asset_export'),

]

crusader/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views
from . import views, settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

app_name = 'crusader'
urlpatterns = [
path('', views.index),
    path('admin/', admin.site.urls),
    path('po/', include('po.urls')),
    path('products/', include('products.urls')),
    path('assets/', include('assets.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

po/urls.py
from django.urls import path
from . import views
from .views import CreateView, DetailView


app_name = 'po'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('create/', views.CreateView.as_view(), name='create'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:po_id>/process/', views.process_po, name='process_po'),

]

assets/models.py
from django import forms
from django.contrib.auth.models import User
from django.db import models
from datetime import datetime

from django.utils import timezone

# Create your models here.
from django.utils.timezone import now

from po.models import Po, Branch


class Status(models.Model):
    title = models.CharField(max_length=50)


class Assets(models.Model):
    STATUS_CHOICES = ("ACTIVE", "SCRAPPED", "FIXING")

    product_name = models.CharField(max_length=55)
    procurement_date = models.DateField('date created', default=timezone.now)
    warranty_expiration = models.DateField('warranty expiration', null=True)
    product_type = models.CharField(max_length=55)
    # product_user = models.CharField(max_length=55)
    po = models.ForeignKey(Po, on_delete=models.CASCADE, null=True)
    invoice_number = models.IntegerField()
    vendor_name = models.CharField(max_length=55)
    status = models.CharField(max_length=55, default="Active")

    notes = models.CharField(max_length=100)
    serial_no = models.CharField(max_length=100)
    branch = models.ForeignKey(Branch, on_delete=models.CASCADE)
    print(warranty_expiration)

    def warranty_status(self, *args):
        date = datetime.date(datetime.now())
        if date > self.warranty_expiration:
            print('true')
            return 'Warranty expired'
        else:
            return 'In Warranty'


class AssetHistory(models.Model):
    old_branch = models.ForeignKey(Branch, on_delete=models.CASCADE, related_name='old_branch')
    old_status = models.CharField(max_length=50)
    old_notes = models.CharField(max_length=200)
    new_branch = models.ForeignKey(Branch, on_delete=models.CASCADE, related_name= 'new_branch')
    new_status = models.CharField(max_length=50)
    new_notes = models.CharField(max_length=200)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    asset = models.ForeignKey(Assets, on_delete=models.CASCADE)
    modified_at = models.DateTimeField(default=now, blank=True)

    def changePhrase(self):
        formatedDate = self.modified_at.strftime("%Y-%m-%d")
        formatedTime = self.modified_at.strftime("%H:%M")

        phrase = []
        if self.old_branch_id != self.asset.branch_id:
            branch_change = f"{formatedDate} : {self.user} changed asset branch from {self.old_branch.Name} to {self.new_branch.Name} at {formatedTime}."
            phrase.append(branch_change)

        if self.old_status != self.new_status:
            status_change = f"{formatedDate} : {self.user} changed asset status from {self.old_status} to {self.new_status} at {formatedTime}."
            phrase.append(status_change)

        if self.old_notes != self.new_notes:
            notes_change = f"{formatedDate} : {self.user} changed asset notes from {self.old_notes} to {self.new_notes} at {formatedTime}."
            phrase.append(notes_change)

        return phrase


class UrAssets(models.Model):
    product_name = models.CharField(max_length=100)
    procurement_date = models.DateField('date created', default=datetime.now, null=True)
    branch = models.ForeignKey(Branch, on_delete=models.CASCADE)
    product_type = models.CharField(max_length=55, null=True)
    po = models.ForeignKey(Po, on_delete=models.CASCADE)
    vendor_name = models.CharField(max_length=55)

assets/forms.py
from django import forms
from django.forms import ModelForm

from po.models import Branch
from .models import Assets


# class AssetForm(forms.ModelForm):
#     class Meta:
#         model = Assets
#         template_name = 'add_assets.html'
#         fields = [
#             'product_name',
#             'procurement_date',
#             'warranty_expiration',
#             'branch_assigned',
#             'product_type',
#             # 'life_expectancy',
#             # product_user
#             # 'po_number',
#             'invoice_number',
#             'vendor_name',
#             'notes'
#         ]
#
#     def __init__(self, *args, **kwargs):
#         super().__init__(*args, **kwargs)
#         self.fields['branch_assigned'].queryset = Branch.objects.all()

assets/views.py
import csv

from po.models import Branch, Vendor
from products.models import Product, Type
from .filters import AssetsFilter, UrAssetsFilter
from .models import Assets, UrAssets, AssetHistory
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views.generic import (CreateView, DeleteView, DetailView, ListView, UpdateView)
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


# Create your views here.

class IndexView(ListView):
    model = Assets
    template_name = 'assets_list.html'
    context_object_name = 'context'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filter'] = AssetsFilter(self.request.GET, queryset=self.get_queryset())
        count = 0

        for asset in context['filter'].qs:
            count += 1
        context['result_count'] = count
        return context


# class AssetExportView(IndexView):
#     template_name = 'SavedSamples.csv'
#     content_type = 'text/csv'
# response = HttpResponse(content_type='text/csv')
# response['Content-Disposition'] = 'attachment;filename="users.csv"'
# writer = csv.writer(response)
# writer.writerow(
#     ['product_name', 'branch__Name', 'procurement_date', 'warranty_expiration', 'product_type', 'po__po_number',
#     'invoice_number',
#     'vendor_name', 'status', 'notes', 'serial_no'])
# assets = context['filter'].qs.values_list('product_name', 'branch__Name', 'procurement_date', 'warranty_expiration',
#                                     'product_type', 'po__po_number', 'invoice_number',
#                                     'vendor_name', 'status', 'notes', 'serial_no')
# for asset in assets:
#     writer.writerow(asset)
# return response

def asset_export(request):
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment;filename="users.csv"'
    writer = csv.writer(response)
    writer.writerow(
        ['product_name', 'branch__Name', 'procurement_date', 'warranty_expiration', 'product_type', 'po__po_number',
         'invoice_number',
         'vendor_name', 'status', 'notes', 'serial_no'])
    assets = Assets.objects.all().values_list('product_name', 'branch__Name', 'procurement_date', 'warranty_expiration',
                                              'product_type', 'po__po_number', 'invoice_number',
                                              'vendor_name', 'status', 'notes', 'serial_no')
    for asset in assets:
        writer.writerow(asset)
    return response


def add_view(request):
    product_types = Type.objects.all().order_by('title')
    branches = Branch.objects.all().order_by('Name')
    vendors = Vendor.objects.all().order_by('Name')

    if request.method == 'POST':
        assets = Assets()
        assets.product_name = request.POST.get('product_name')
        assets.po_number = request.POST.get('po_number')
        assets.serial_no = request.POST.get('serial_no')
        assets.procurement_date = request.POST.get('procurement_date')
        assets.warranty_expiration = request.POST.get('warranty_expiration')
        assets.branch_id = request.POST.get('branch_dropdown')
        assets.product_type = request.POST.get('product_dropdown')
        assets.invoice_number = request.POST.get('invoice_number')
        assets.vendor_id = request.POST.get('vendor_dropdown')
        assets.notes = request.POST.get('notes')
        assets.po = request.POST.get('po_number')
        assets.save()
        return HttpResponseRedirect(reverse('assets:asset_detail_view', args=(assets.id,)))
    else:
        return render(request, 'add_assets.html',
                      {'branches': branches, 'product_types': product_types, 'vendors': vendors})


def ura_to_asset_view(request, ura_id):
    ura = get_object_or_404(UrAssets, pk=ura_id)
    branches = Branch.objects.all().order_by('Name')

    if request.method == 'POST':
        assets = Assets()
        assets.product_name = request.POST.get('product_name')
        assets.po_number = request.POST.get('po_number')
        assets.serial_no = request.POST.get('serial_no')
        assets.procurement_date = request.POST.get('procurement_date')
        assets.warranty_expiration = request.POST.get('warranty_expiration')
        assets.branch_id = ura.branch_id
        assets.product_type = request.POST.get('product_type')
        assets.invoice_number = request.POST.get('invoice_number')
        assets.vendor_name = request.POST.get('vendor_name')
        assets.notes = request.POST.get('notes')
        # assets.po_number = request.POST.get('po_number')
        assets.po_id = ura.po_id
        assets.save()

        ura.delete()
        return HttpResponseRedirect(reverse('assets:asset_detail_view', args=(assets.id,)))
    else:
        return render(request, 'add_assets.html', {'branches': branches, 'ura': ura})


# def add_view(request):
#     form = AssetForm(request.POST or None)
#     if form.is_valid():
#         form.save()
#         #form = AssetForm
#     context = {
#         'form': form
#     }
#     return render(request, 'add_assets.html', context)


class UrAView(ListView):
    model = UrAssets
    template_name = 'ur_assets_list.html'
    paginate_by = 10

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filter'] = UrAssetsFilter(self.request.GET, queryset=self.get_queryset().order_by('-procurement_date'))
        count = 0
        for asset in context['filter'].qs:
            count += 1
        context['result_count'] = count
        return context


# class AssetDetailView(DetailView):
#     model = Assets
#     template_name = 'asset_detail_view.html'

def asset_detail_view(request, asset_id):
    asset = get_object_or_404(Assets, pk=asset_id)
    asset_histories = AssetHistory.objects.filter(asset_id=asset_id).order_by('-modified_at')
    return render(request, 'asset_detail_view.html', {'asset_histories': asset_histories, 'asset': asset})


# def asset_update_view(request, asset_id):
#     asset =get_object_or_404(Assets, pk=asset_id)
#     branch = Branch.objects.all()
#     print(asset.product_name)
#     return render(request, 'assets_form.html', {'asset':asset, 'branch':branch})

def asset_update_view(request, asset_id):
    asset = get_object_or_404(Assets, pk=asset_id)
    branches = Branch.objects.all().order_by('Name')
    asset_instance = AssetHistory()
    asset_instance.old_branch_id = asset.branch_id
    asset_instance.old_status = asset.status
    asset_instance.old_notes = asset.notes

    if request.method == 'POST':
        user = request.user
        print(user)
        asset.branch_id = request.POST.get('branch_dropdown')
        asset.status = request.POST.get('status').capitalize()
        asset.notes = request.POST.get('notes')
        asset.save()
        asset = get_object_or_404(Assets, pk=asset_id)
        asset_instance.new_branch_id = asset.branch_id
        asset_instance.new_status = asset.status
        asset_instance.new_notes = asset.notes
        asset_instance.user_id = user.id
        asset_instance.asset_id = asset_id
        asset_instance.save()
        return HttpResponseRedirect(reverse('assets:asset_detail_view', args=(asset_id,)))
    else:
        return render(request, 'assets_form.html', {'branches': branches, 'asset': asset})

assets/templates/add_assets.html
{% extends 'base.html' %}
{#{% load crispy_forms_tags %}#}
{#{% load crispy_forms_field %}#}




{% block content %}
    <h2 class="mt-4 mb-4 font-weight-bold text-primary">Add New Asset</h2>
    <div class="container border bg-dark">
        <form method="POST">
            {% csrf_token %}
            <div class="form-row mt-3">

                <div class="form-group text-white disabled col-md-6 ">
                    {% if not ura.id %}
                        <label for="product_name"><strong>Product Title</strong></label>
                        <input type="text" class="form-control text-center" value="{{ ura.product_name }}" id="product_name"
                               name='product_name'
                               placeholder="Product Title">
                    {% endif %}
                    {% if ura.id %}
                        <label for="product_name"><strong>Product Title</strong></label>
                        <input type="text" class="form-control text-center" value="{{ ura.product_name }}" id="product_name"
                               name='product_name'
                               placeholder="Product Title" readonly>
                    {% endif %}
                </div>

                <div class="form-group text-white col-md-3">
{#                    {% if not ura.id %}#}
{#                        <label for="vendor_name"><strong>PO number</strong></label>#}
{#                        <input type="text" class="form-control" value="{{ ura.po.po_number }}" id="po_number"#}
{#                               name='po_number'#}
{#                               placeholder="Po No">#}
{#                    {% endif %}#}
                    {% if ura.id %}
                        <label for="vendor_name"><strong>PO number</strong></label>
                        <input type="text" class="form-control text-center" value="{{ ura.po.po_number }}" id="po_number"
                               name='po_number'
                               placeholder="Po No" readonly>
                    {% endif %}

                </div>

                <div class="form-group text-white col-md-3">
                    <label for="invoice_number"><strong>Invoice number</strong></label>
                    <input type="int" class="form-control text-center" id="invoice_number" name="invoice_number"
                           placeholder="Invoice No">
                </div>

            </div>
            <div class="form-row">
                <div class="form-group text-white col-md-3">
                    <label for="serial_no"><strong>Serial Number</strong></label>
                    <input type="text" class="form-control text-center" id="branch_assigned" name='serial_no'
                           placeholder="Serial No">
                </div>

                <div class="form-group text-white col-md-3">
                    {% if not ura.id %}
                        <label for="branch_assigned"><strong>Branch Assigned</strong></label>
                        <select name="branch_dropdown" class="form-control">
                            {% for branch in branches %}
                                <option class="dropdown-item text-center" value="{{ branch.pk }}">{{ branch.Name }}</option>
                            {% endfor %}
                        </select>
                    {% endif %}
                    {% if ura.id %}
                        <label for="branch_assigned"><strong>Branch Assigned</strong></label>
                        <input type="text" class="form-control text-center" value="{{ ura.branch.Name }}" id="branch_assigned"
                               name='branch_assigned'
                               placeholder="Branch Assigned" readonly>
                    {% endif %}
                </div>

                <div class="form-group text-white col-md-3">
                    {% if not ura.id %}
                        <label for="product_type"><strong>Product Type</strong></label>
                        <select name="product_dropdown" class="form-control ">
                            {% for type in product_types %}
                                <option class="dropdown-item text-center" value="{{ type.title }}">{{ type.title }}</option>
                            {% endfor %}
                        </select>
                    {% endif %}
                    {% if ura.id %}
                        <label for="Product Type"><strong>Product Type</strong></label>
                        <input type="text" class="form-control text-center" value="{{ ura.product_type.title }}" id="product_type"
                               name='product_type' placeholder="Product Type" readonly>
                    {% endif %}
                </div>
                <div class="form-group text-white col-md-3">
                    {% if not ura.id %}
                        <label for="vendor_dropdown"><strong>Vendor Name</strong></label>
                        <select name="vendor_dropdown" class="form-control">
                            {% for vendor in vendors %}
                                <option class="dropdown-item text-center" value="{{ vendor.name }}">{{ vendor.Name }}</option>
                            {% endfor %}
                        </select>
                    {% endif %}
                    {% if ura.id %}
                        <label for="vendor_name"><strong>Vendor Name</strong></label>
                        <input type="text" class="form-control text-center" value="{{ ura.vendor_name }}" id="vendor_name"
                               name='vendor_name'
                               placeholder="Vendor Name" readonly>
                    {% endif %}
                </div>

            </div>
            <div class="form-row">
                <div class="form-group text-white col-md-3">
                    <label for="procurement_date"><strong>Procurement Date</strong></label>
                    <input type="date" class="form-control text-center" id="procurement_date"
                           name="procurement_date">
                </div>
                <div class="form-group text-white col-md-3">
                    <label for="warranty_expiration"><strong>Warranty Expiration</strong></label>
                    <input type="date" class="form-control text-center" id="warranty_expiration"
                           name="warranty_expiration">
                </div>
                <div class="col-md-3 text-white">
                    <label for="notes"><strong>Notes</strong></label>
                    <input type="text" class="form-control text-center" id="notes" placeholder="Notes" name="notes">
                </div>
            </div>
            <input type="submit" value="Save" class=" mb-3 btn btn-primary"/>
        </form>
    </div>
{% endblock %}

assets/templates/assets_list.html
{% extends 'base.html' %}
{% load bootstrap %}
{% load widget_tweaks %}

{% block content %}
    <div class="row">
        <div><h2 class="mt-4 mb-4 font-weight-bold text-primary">Asset Report</h2></div>
        <div class="col-sm-5 form-group text-right col-md-4 mt-4">
            <a type="button" class="btn btn-sm btn-outline-info btn-lg"
               href="{% url "assets:asset_export"  %}">Export</a>
        </div>
    </div>

    <form method="get">
        <div class="well">
            <div class="row">
                <div class="form-group col-sm-4 col-md-3">
                    <strong>{{ filter.form.product_type.label_tag }}</strong>
                    {% render_field filter.form.product_type class="form-control" %}<br>
                    <div class="ml-3">
                        <button type="submit" class="btn btn-primary">Search</button>
                    </div>
                </div>
                <div class="form-group col-sm-4 col-md-3 row">
                    <strong>{{ filter.form.branch__Name.label_tag }}</strong>
                    {% render_field filter.form.branch__Name class="form-control" %}<br>
                    <div class="form-group text-center col-sm-2 col-md-4 mt-4">
                        <label for="invoice_number"><strong>Results:</strong></label>
                    </div>
                    <div class="form-group col-md-4 mt-4"><input type="int" class="form-control"
                                                                 id="invoice_number" name="invoice_number"
                                                                 placeholder="Count" value="{{ result_count }}"
                                                                 readonly>
                    </div>
                </div>
                <div class="form-group col-sm-2 col-md-3">
                    <strong>{{ filter.form.status.label_tag }}</strong>
                    {% render_field filter.form.status class="form-control" %}
                </div>
                <div class="form-group col-sm-2 col-md-3">
                    <strong>{{ filter.form.procurement_date.label_tag }}</strong>
                    {% render_field filter.form.procurement_date class="form-control" %}
                </div>
            </div>
        </div>
    </form>
    <table class="table table-hover table-bordered table-dark">
        <thead>
        <tr>
            <th class='bg-primary text-center text-white' scope="col">Sno.</th>
            <th class='bg-primary text-center text-white' scope="col">Product</th>
            <th class='bg-primary text-center text-white' scope="col">Product Type</th>
            <th class='bg-primary text-center text-white' scope="col">Branch</th>
            <th class='bg-primary text-center text-white' scope="col">PO Number</th>
            <th class='bg-primary text-center text-white' scope="col">Status</th>
            <th class='bg-primary text-center text-white' scope="col">Warranty</th>
            <th class='bg-primary text-center text-white' scope="col">Actions</th>
        </tr>
        </thead>
        <tbody>
        <form>
        </form>
        {% for asset in filter.qs %}
            <tr>
                <th class="text-center" scope="row">{{ forloop.counter }}</th>
                <td><a scope="row"
                       href={% url 'assets:asset_detail_view' asset.id %}>{{ asset.product_name }}</a></td>
                <td>{{ asset.product_type }}</td>
                <td>{{ asset.branch }}</td>
                <td class="text-center "><a scope="row"
                        {% if asset.po.id %}
                                            href={% url 'po:detail' asset.po.id %}>{{ asset.po.po_number }}</a>
                        {% endif %}
                    {% if not asset.po.id %}
                        <p class="text-warning">Manual Purchase</p>
                    {% endif %}</td>
                {% if asset.status == "Active" %}
                    <td class="text-center">
                        <div class="badge badge-success">{{ asset.status }}</div>
                    </td>
                {% endif %}
                {% if asset.status == "Scrapped" %}
                    <td class="text-center">
                        <div class="badge badge-secondary">{{ asset.status }}</div>
                    </td>
                {% endif %}
                {% if asset.status == "Fixing" %}
                    <td class="text-center">
                        <div class="badge badge-warning ">{{ asset.status }}</div>
                    </td>
                {% endif %}

                <td class="text-center ">{{ asset.warranty_status }}</td>
                <td class="text-center"><a type="button" class="btn btn-sm btn-outline-info btn-lg"
                                           href="{% url "assets:asset_update_view" asset.id %}">Update</a></td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    {% if is_paginated %}
        <ul class="pagination">
            {% if page_obj.has_previous %}
                <li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
            {% else %}
                <li class="disabled"><span>&laquo;</span></li>
            {% endif %}
            {% for i in paginator.page_range %}
                {% if page_obj.number == i %}
                    <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
                {% else %}
                    <li><a href="?page={{ i }}">{{ i }}</a></li>
                {% endif %}
            {% endfor %}
            {% if page_obj.has_next %}
                <li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
            {% else %}
                <li class="disabled"><span>&raquo;</span></li>
            {% endif %}
        </ul>
    {% endif %}

{% endblock %}

assets/templates/ur_assets_list.html
{% extends 'base.html' %}
{% load bootstrap %}
{% load widget_tweaks %}


{% block content %}
    <h2 class="mt-5 mb-5 font-weight-bold text-primary">UR Asset Report</h2>
    <form method="get">
        <div class="well">
            <div class="row">
                <div class="form-group col-sm-4 col-md-3">
                    <strong>{{ filter.form.product_type.label_tag }}</strong>
                    {% render_field filter.form.product_type class="form-control" %}
                </div>
                <div class="form-group col-sm-4 col-md-3">
                    <strong>{{ filter.form.vendor_name.label_tag }}</strong>
                    {% render_field filter.form.vendor_name class="form-control" %}
                </div>
                <div class="form-group col-sm-2 col-md-3">
                    <strong>{{ filter.form.po__po_number.label_tag }}</strong>
                    {% render_field filter.form.po__po_number class="form-control" %}
                </div>
                <div class="form-group text-center col-md-1 mb-4">
                     <label for="invoice_number"><strong>Results</strong></label>

                    <input type="int" class="form-control" id="invoice_number" name="invoice_number"
                           placeholder="Count" value="{{ result_count }}" readonly>
                </div>
                <div class="form-group mt-4 mb-4 float-right">
                    <button type="submit" class="btn btn-primary btn-lg mr-4 float-right">
                        <span class="glyphicon glyphicon-search"></span> Search
                    </button>
                </div>
            </div>


    </form>

    <table class="table mt-4 table-hover table-bordered table-dark">
        <thead>
        <tr>
            <th class='bg-primary text-center text-white' scope="col">Sno.</th>
            <th class='bg-primary text-center text-white' scope="col">Product</th>
            <th class='bg-primary text-center text-white' scope="col">Product Type</th>
            <th class='bg-primary text-center text-white' scope="col">Vendor</th>
            <th class='bg-primary text-center text-white' scope="col">Po Number</th>
            <th class='bg-primary text-center text-white' scope="col">Actions</th>

        </tr>
        </thead>
        <tbody>
        <form>

        </form>
        {% for ura in filter.qs %}
            <tr>
                <th class="text-center" scope="row">{{ forloop.counter }}</th>
                <td class="text-center">{{ ura.product_name }}</td>
                <td class="text-center">{{ ura.product_type }}</td>
                <td class="text-center">{{ ura.vendor_name }}</td>
                <td class="text-center "><a scope="row" href={% url 'po:detail' ura.po.id %}>{{ ura.po.po_number }}</a></td>
                <td class="text-center"><a class="btn btn-sm  btn-primary text-center"
                                           href="{% url 'assets:ura_asset_add' ura.id %}">Add Asset</a></td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

{% endblock %}