crusader/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views
from . import views, settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

app_name = 'crusader'
urlpatterns = [
path('', views.index),
    path('admin/', admin.site.urls),
    path('po/', include('po.urls')),
    path('products/', include('products.urls')),
    path('assets/', include('assets.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

po/urls.py
from django.urls import path
from . import views
from .views import CreateView, DetailView


app_name = 'po'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('create/', views.CreateView.as_view(), name='create'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:po_id>/process/', views.process_po, name='process_po'),

]

po/models.py
from datetime import datetime
from django.apps import apps
from django.contrib.auth.models import User
from django.db import models
from products.models import Product, Make


class Departments(models.Model):
    title = models.CharField(max_length=100)

    def __str__(self):
        return self.title


class Designations(models.Model):
    title = models.CharField(max_length=100)
    department = models.ForeignKey(Departments, on_delete=models.CASCADE)

    def __str__(self):
        return self.title


class Employee(models.Model):
    name = models.CharField(max_length=100)
    designation = models.ForeignKey(Designations, on_delete=models.CASCADE)
    department = models.ForeignKey(Departments, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Branch(models.Model):
    Name = models.CharField(max_length=100)
    phone = models.BigIntegerField()
    email = models.EmailField()
    # address
    door_no = street_address = models.CharField(max_length=100)
    street_address = models.CharField(max_length=100)
    road_address = models.CharField(max_length=100)

    apartment_address = models.CharField(max_length=100)
    zip = models.CharField(max_length=100)

    def __str__(self):
        return self.Name


class Vendor(models.Model):
    Name = models.CharField(max_length=100)
    phone = models.BigIntegerField()
    email = models.EmailField()
    # address
    door_no = street_address = models.CharField(max_length=100)
    street_address = models.CharField(max_length=100)
    road_address = models.CharField(max_length=100)
    apartment_address = models.CharField(max_length=100)
    zip = models.CharField(max_length=100)

    def __str__(self):
        return self.Name


# def get_product_price(*args):
#     products = Product.objects.filter(id='id')
#     unit_price = products.price
#     return unit_price


class PoItem(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)
    price = models.DecimalField(max_digits=10, decimal_places=2)

    def get_total_price(self):
        return self.quantity * self.price

    def __str__(self):
        return f"{self.quantity} of {self.product.title}"


def increment_po_number():
    last_po = Po.objects.all().order_by('id').last()
    if not last_po:
        return 'DNCIT2020-001'
    po_number = last_po.po_number
    po_int = int(po_number.split('DNCIT2020-')[-1])
    new_po_int = po_int + 1

    new_po_number = 'DNCIT2020-' + str('{0:03}'.format(new_po_int))
    return new_po_number


class Po(models.Model):
    po_item = models.ManyToManyField(PoItem)
    passer = models.ForeignKey(Employee, on_delete=models.CASCADE, related_name='passer')
    approved_by = models.ForeignKey(Employee, on_delete=models.CASCADE, related_name='approved_by')
    department = models.ForeignKey(Departments, on_delete=models.CASCADE)
    vendor = models.ForeignKey(Vendor, on_delete=models.CASCADE)
    branch = models.ForeignKey(Branch, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateField(auto_now_add=True)
    processed = models.BooleanField(default=False)
    po_number = models.CharField(max_length=25, default=increment_po_number)
    processed_date = models.DateTimeField(auto_now_add=True, blank=True)

    def total_cost(self):
        po_items = self.po_item.all()
        cost = 0
        for po_item in po_items:
            cost += po_item.get_total_price()
        return cost


    def __int__(self, po_number):
        return self.po_number()

po/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from django.views.generic import (CreateView, DeleteView, DetailView, ListView, UpdateView)
from products.models import Product
from .filters import PoFilter
from .models import Po, PoItem
from assets.models import UrAssets
from datetime import datetime


class IndexView(ListView):
    model = Po
    template_name = 'poList.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filter'] = PoFilter(self.request.GET, queryset=self.get_queryset().order_by('processed'))
        # print(PoFilter(self.request.GET, queryset=self.get_queryset().order_by('processed')).qs)
        total = 0
        for po in context['filter'].qs:
            total+=po.total_cost()
        context['total'] = total
        return context


class CreateView(CreateView):
    model = Po
    template_name = 'createPo.html'


class DetailView(DetailView):
    model = Po
    template_name = 'po_template.html'


class DeleteView(generic.DeleteView):
    model = Po
    template_name = 'poList.html'


def process_po(request, po_id):
    po = get_object_or_404(Po, pk=po_id)
    po_item = PoItem.objects.all().filter(po=po_id)

    for items in po_item:
        product = get_object_or_404(Product, id=items.product_id)
        while items.quantity > 0:
            product_title = str(product.make) + '-' + str(product.model_name)
            print(product_title)
            ura = UrAssets(po_id=po.id, vendor_name=po.vendor, product_name=product_title,
                           product_type=product.product_type, branch_id=po.branch.id)
            ura.save()
            items.quantity -= 1

    print(po.__dict__)

    po.processed = True
    po.processed_date = datetime.now()
    po.save()

    return HttpResponseRedirect(reverse('po:index'))

po/templates/createPo.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Create New Purchase Order</div>

                <div class="card-body">
                    <form action="/po" method="post">
{% csrf_token %}

                        <div class="form-group">
                        Product Name:    <input aria-describedby="questionHelp" class="form-control"
                                   id="product" name="productName" placeholder="Enter Product Name"
                                   type="text">
                        </div>


                        <div>
                            <div class="form-group">
                            Model No :    <input aria-describedby="answer2Help" class="form-control" id="answer2"
                                       name="answers[][answer]" placeholder="Enter Model No" type="text"
                                       value="">
                            </div>
                        </div>


                        <div>
                            <div class="form-group">
                            Count :    <input aria-describedby="answer1Help" class="form-control" id="answer1"
                                       name="answers[][answer]" placeholder="Enter Number of Items" type="text"
                                       value="">
                            </div>
                        </div>


                        <div>
                            <div class="form-group">
                               Price : <input aria-describedby="answer2Help" class="form-control" id="answer3"
                                       name="answers[][answer]" placeholder="Enter Price" type="text"
                                       value="">

                            </div>
                        </div>


                        <div>
                            <div class="form-group">
                             Delivery Address :   <input aria-describedby="answer2Help" class="form-control" id="answer4"
                                       name="answers[][answer]" placeholder="Enter Delivery Address" type="text"
                                       value="">

                            </div>
                        </div>


                <button class="btn btn-primary" type="submit">Add PO</button>

                </form>
            </div>
        </div>
    </div>
</div>
</div>
{% endblock %}

po/templates/poList.html
{% extends 'base.html' %}
{% load bootstrap %}
{% load widget_tweaks %}

{% block content %}
    <h2 class="mt-5 mb-5 text-primary"><strong>Purchase Orders</strong></h2>
     <form method="get">
    <div class="well">
      <div class="row">

        <div class="form-group col-sm-4 col-md-3">
          <strong>{{ filter.form.po_number.label_tag }}</strong>
          {% render_field filter.form.po_number class="form-control" %} <br>
            <div class="row ml-2">
            <button type="submit" class="btn btn-primary mb-4 ml-4">
            <span class="glyphicon glyphicon-search"></span> Search
      </button></div>
        </div>
        <div class="form-group col-sm-2 col-md-3">
          <strong>{{ filter.form.approved_by.label_tag }}</strong>
          {% render_field filter.form.approved_by class="form-control" %}
        </div>
        <div class="form-group col-sm-4 col-md-3">
          <strong>{{ filter.form.processed.label_tag }}</strong>
          {% render_field filter.form.processed class="form-control" %}
        </div>
      <div class="form-group col-sm-4 col-md-3">
          <strong>{{ filter.form.created_at.label_tag }}</strong>
          {% render_field filter.form.created_at class="form-control" %}
        </div>
      </div>


    </div>
  </form>
    <table class="table table-hover table-bordered table-dark">
        <thead>
        <tr>
            <th class='bg-primary text-center text-white' scope="col">PO Number</th>
            <th class='bg-primary text-center text-white' scope="col">Products</th>
            <th class='bg-primary text-center text-white' scope="col">Price</th>
            <th class='bg-primary text-center text-white' scope="col">Qty</th>
            <th class='bg-primary text-center text-white' scope="col">Total</th>
            <th class='bg-primary text-center text-white' scope="col">Actions</th>
        </tr>
        </thead>
        <tbody>
        {% for po in filter.qs %}
            <tr>
                <th class="text-center"><a  scope="row" href={% url 'po:detail' po.id %}>{{ po.po_number }}</a></th>
                <td>
                    {% for item in po.po_item.all %}
                        {{ item.product.title }}
                        <br>
                    {% endfor %}
                </td>
                <td class="text-right">{% for item in po.po_item.all %}
                    ₹ {{ item.get_total_price }}
                    <br>
                {% endfor %}
                </td>
             <td class="text-center">{% for item in po.po_item.all %}
                     {{ item.quantity }}
                    <br>
                {% endfor %}
                </td>
                <td class="text-right"> ₹ {{ po.total_cost }}</td>
            {% if po.processed == True %}
            <td class="text-center">
                    <a class="btn btn-sm disabled btn-secondary" href=''>Processed</a>
                </td>
            </tr>
            {% endif %}
            {% if po.processed == False %}
             <td class="text-center">
                    <a class="btn btn-sm btn-primary" href={% url 'po:process_po' po.id %}>Process</a>
                </td>
            {% endif %}

            </tr>
        {% endfor %}
        <td colspan="3"></td>
        <th  class="text-center">Total</th>
        <th class="text-right">₹ {{ total }}</th>
        </tbody>
        </tbody>
    </table>
    </div>
{% endblock %}

po/templates/po_template.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <style>
        img {
            width: 30%;
            height: 50%;
            object-fit: contain;
        }
    </style>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Purchase Order</title>
</head>
<body>
</body>
</html>
<div class="container border">
    <p>
        <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSqlEJ99Hmx2BvYFRIp3Fqk3lsjR0kxU8l7E3PmcqF8z5h3I9s9" class="rounded float-right img mr-4 mt-5" alt="DNC CHITS Pvt. Ltd.">
    </p>
    <div class="row  mt-4">
        <div class="col-sm-6">
            <div class="card border-primary mt-5">
                <div class="card-body">
                    <h5 class="card-title text-warning"><strong>DNC Chits Pvt. Ltd,</strong></h5>
                  <p class="card-text">No. 49/14 <br> North Boag Road, <br> B, Narasimman Road, <br> T. Nagar, Chennai -
                        600017.</p>
                </div>
            </div>
        </div>
        <div class="col-sm-6">
            <div class="card border-primary mr-3 ml-5 mt-5">
                <div class="card-body">
                    <h5 class="card-title text-warning"><strong>Purchase Order</strong></h5>
                    <p class="card-text">PO No : {{po.po_number}} <br>Date : {{ po.created_at }}</p>
                </div>
            </div>
        </div>
    </div>
    <br>
    <div class="row mt-5">
        <div class="col-sm-6">
            <div class="card">
                <div class="card-header text-white bg-primary mb-3"><strong>Vendor Details</strong></div>

                <div class="card-body">
                    <h5 class="card-title">{{ po.vendor.Name }},</h5>
                  <p class="card-text">{{ po.vendor.door_no }}, <br> {{ po.vendor.street_address }}, <br> {{ po.vendor.road_address }}, <br> {{ po.vendor.apartment_address }}
                        - {{ po.vendor.zip }}.</p>
                    <p class="card-text">Phone : {{po.vendor.phone}} <br> Email: {{ po.vendor.email }}</p>
                </div>
            </div>
        </div>
        <div class="col-sm-6">
            <div class="card">
                <div class="card-header text-white bg-primary mb-3"><strong>Delivery Address</strong></div>
                <div class="card-body">
                    <h5 class="card-title">DNC Chits Pvt. Ltd,</h5>
                  <p class="card-text">{{ po.branch.door_no }}, <br> {{ po.branch.street_address }}, <br> {{ po.branch.road_address }},<br> {{ po.branch.apartment_address }}
                        - {{ po.branch.zip }}.</p>
                    <p class="card-text">Phone : {{ po.branch.phone }} <br> Email: {{ po.branch.email }}</p>
                </div>
            </div>
        </div>
    </div>
    <br>
    <br>

    <table class="table table-bordered mt-4">
        <thead>
        <tr>
            <th class="bg-primary mb-3 text-center" scope="col">PO No</th>
            <th class="bg-primary mb-3 text-center" scope="col">Requested By</th>
            <th class="bg-primary mb-3 text-center" scope="col">Approved By</th>
            <th class="bg-primary mb-3 text-center" scope="col">Department</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td class="text-center">{{ po.po_number }}</td>
            <td class="text-center">{{ po.passer }}</td>
            <td class="text-center">{{ po.approved_by }}</td>
            <td class="text-center">{{ po.department }}</td>
        </tr>

        </tbody>
    </table>
    <br>
    <table class="table table-centered table-striped table-bordered mt-4 mb-4">
       <tbody>
        <tr>
            <td class="text-center bg-primary"><strong>Sno</strong></td>
            <td class="text-center bg-primary"><strong>Product</strong></td>
            <td class="text-center bg-primary"><strong>Quantity</strong></td>
            <td class="text-center bg-primary"><strong>Unit Price</strong></td>
            <td class="text-center bg-primary"><strong>Total</strong></td>
        </tr>


        {% for item in po.po_item.all %}
            <tr>
                <td class="text-center">{{ forloop.counter }}</td>
                <td class="text-center">{{ item.product.title }}</td>
                <td class="text-center">{{ item.quantity }}</td>
                <td class="text-right">₹ {{ item.price }}</td>
                <td class="text-right">₹ {{ item.get_total_price }}</td>
            </tr>
        {% endfor %}
        <td colspan="3"></td>
        <th  class="text-center">Total</th>
        <td class="text-right">₹ {{ po.total_cost }}</td>
        </tbody>

    </table>
    <div class="card float-right mt-5 mr-3 mb-5" style="width: 14rem;">
        <div class="card-header bg-primary text-white text-center">
            <strong>Authorised Signatory</strong>
        </div>
        <ul class="list-group list-group-flush">
            <li class="list-group-item text-center">{{po.approved_by}}</li>
        </ul>
    </div>
</div>