assets/urls.py
from django.contrib import admin
from django.urls import path, include
from assets import views

app_name = "assets"
urlpatterns = [
    path('add/', views.add_view, name='asset_add'),
    path('ur/<int:ura_id>/add/', views.ura_to_asset_view, name='ura_asset_add'),
    path('list/', views.IndexView.as_view(), name='asset_list'),
    path('ur/list/', views.UrAView.as_view(), name='ur_asset_list'),
    path('<int:asset_id>/', views.asset_detail_view, name='asset_detail_view'),
    path('<int:asset_id>/update', views.asset_update_view, name='asset_update_view'),
    path('export/$', views.asset_export, name='asset_export'),

]

crusader/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views
from . import views, settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

app_name = 'crusader'
urlpatterns = [
path('', views.index),
    path('admin/', admin.site.urls),
    path('po/', include('po.urls')),
    path('products/', include('products.urls')),
    path('assets/', include('assets.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

po/urls.py
from django.urls import path
from . import views
from .views import CreateView, DetailView


app_name = 'po'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('create/', views.CreateView.as_view(), name='create'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:po_id>/process/', views.process_po, name='process_po'),

]

templates/base.html
<!doctype html>
{% load static %}

<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/index.css' %}">


    <title class="text-weight-bold">Crusader</title>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        <a class="navbar-brand" href='/'><strong>CRUSADER</strong></a>
        <button aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"
                class="navbar-toggler"
                data-target="#navbarSupportedContent" data-toggle="collapse" type="button">
            <span class="navbar-toggler-icon"></span>
        </button>

        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="/admin/">Admin <span class="sr-only">(current)</span></a>
            </li>

            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
                   aria-haspopup="true" aria-expanded="false">
                    Products
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href='/admin/products/product/'>Products</a>
                    <a class="dropdown-item" href='/admin/products/product/add/'>Add New Product</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="/po/link">Attach PO</a>
                </div>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
                   aria-haspopup="true" aria-expanded="false">
                    PO
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href={% url 'po:index' %}>PO Report</a>
                    <a class="dropdown-item" href="/admin/po/po/add/">Add New PO</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="po/realize">Realize PO</a>
                </div>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
                   aria-haspopup="true" aria-expanded="false">
                    Assets
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href={% url 'assets:asset_add' %}>Add New Asset</a>
                    <a class="dropdown-item" href={% url 'assets:asset_list' %}>Asset Report</a>
                    <a class="dropdown-item" href={% url 'assets:ur_asset_list' %}>UR Assets</a>
                    <div class="dropdown-divider"></div>

                </div>
            </li>
        </ul>
    </div>
</nav>
<div class="container">
    {% block content %}
    {% endblock %}
</div>
</div>
<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
</body>
</html>

templates/index.html
{% extends 'base.html' %}

{% block content %}

    <h1 class="mt-4"><strong>DASHBOARD</strong></h1>

    <div class="row">
        <div class="col-sm-3 mt-4">
            <div class="card text-white bg-dark">
                <div class="card-body">
                    <h5 class="card-title font-weight-bold">Total Assets</h5>
                    <p class="card-text font-weight-bold"><h4> {{ assetCount }}</h4></p>
                    <a href="{% url 'assets:asset_list' %}" class="btn btn-primary">View Assets</a>
                    <div class="icon col-sm-5 mt-5 mr-3">
                        <img src="/media/images/ASSETS.png"
                             width="95px">

                    </div>
                </div>
            </div>
        </div>
        <div class="col-sm-3 mt-4">

            <div class="card text-white bg-dark">
                <div class="card-body">
                    <h5 class="card-title font-weight-bold">UnRealized Assets</h5>
                    <p class="card-text font-weight-bold"><h4> {{ uraCount }}</h4></p>
                    <a href="{% url 'assets:ur_asset_list' %}" class="btn btn-primary stretched-link">UR Assets</a>
                    <div class="icon col-sm-5 mt-5 ">
                        <img src="/media/images/data-pending-1-564533.png"
                             width="65px">
                    </div>
                </div>
            </div>
        </div>
          <div class="col-sm-3 mt-4">
            <div class="card text-white bg-dark">
                <div class="card-body">
                    <h5 class="card-title font-weight-bold">Purchase Orders</h5>
                    <p class="card-text font-weight-bold"><h4>{{ poCount }}</h4></p>
                    <a href="{% url 'po:index' %}" class="btn btn-primary">View Pos</a>
                    <div class="icon col-sm-5 mt-5 ml-2">
                        <img src="/media/ICON/po/sage-fas-illustration-reporting.png" width="60px">

                    </div>
                </div>
            </div>
        </div>
        <div class="col-sm-3 mt-4">
            <div class="card text-white bg-dark">
                <div class="card-body">
                    <h5 class="card-title font-weight-bold">Processed POs</h5>
                    <p class="card-text float-right font-weight-bold"><h4>{{ processed_pos_count }}</h4></p>
                    <a href="http://127.0.0.1:8000/po/?processed=true" class="btn btn-primary">View</a>
                    <div class="icon col-sm-5 mt-5 ml-2">
                        <img src="/media/ICON/po/report-icon.png" width="60px">

                    </div>
                </div>
            </div>
        </div>
        <div class="col-sm-3 mt-4">
            <div class="card text-white bg-dark">
                <div class="card-body">
                    <h5 class="card-title font-weight-bold">UnProcessed POs</h5>
                    <p class="card-text float-right font-weight-bold"><h4>{{ un_processed_pos_count }}</h4></p>
                    <a href="http://127.0.0.1:8000/po/?processed=false" class="btn btn-primary">View</a>
                    <div class="icon col-sm-5 mt-5 ml-2">
                        <img src="/media/images/invoice-icon-54.png" width="60px">

                    </div>
                </div>
            </div>
        </div>
        <div class="col-sm-3 mt-4">
            <div class="card text-white bg-dark">
                <div class="card-body">
                    <h5 class="card-title font-weight-bold">Laptops</h5>
                    <p class="card-text float-right font-weight-bold"><h4>{{ laptop_count }}</h4></p>
                    <a href="http://127.0.0.1:8000/assets/list/?product_type=laptop" class="btn btn-primary">View</a>
                    <div class="icon col-sm-5 mt-5 ml-2">
                        <img src="/media/ICON/assets/lapf.png" width="60px">

                    </div>
                </div>
            </div>
        </div>
        <div class="col-sm-3 mt-4">
            <div class="card text-white bg-dark">
                <div class="card-body">
                    <h5 class="card-title font-weight-bold">Printers</h5>
                    <p class="card-text float-right font-weight-bold"><h4>{{ printer_count }}</h4></p>
                    <a href="http://127.0.0.1:8000/assets/list/?product_type=printer"
                       class="btn btn-primary stretched-link">View</a>
                    <div class="icon col-sm-5 mt-5 ml-2">
                        <img src="/media/ICON/assets/9images.png" width="65px">

                    </div>
                </div>
            </div>
        </div>

        <div class="col-sm-3 mt-4">
            <div class="card text-white bg-dark">
                <div class="card-body">
                    <h5 class="card-title font-weight-bold">Jio-Fi</h5>
                    <p class="card-text float-right font-weight-bold"><h4>{{ jiofi_count }}0</h4></p>
                    <a href="http://127.0.0.1:8000/assets/list/?product_type=printer"
                       class="btn btn-primary stretched-link">View</a>
                    <div class="icon col-sm-5 mt-5 ml-2">
                        <img src="/media/ICON/assets/30a69aefecb699371487f80a5365d90a_icon.png" width="70px">

                    </div>
                </div>
            </div>
        </div>
        <div class="col-sm-3 mt-4">
            <div class="card text-white bg-dark">
                <div class="card-body">
                    <h5 class="card-title font-weight-bold">Monitors</h5>
                    <p class="card-text float-right font-weight-bold"><h4>{{ monitor_count }}0</h4></p>
                    <a href="http://127.0.0.1:8000/assets/list/?product_type=printer"
                       class="btn btn-primary stretched-link">View</a>
                    <div class="icon col-sm-5 mt-5 ml-2">
                        <img src="/media/ICON/assets/imges%20.png" width="55px">

                    </div>
                </div>
            </div>
        </div>
    <div class="col-sm-3 mt-4">
            <div class="card text-white bg-dark">
                <div class="card-body">
                    <h5 class="card-title font-weight-bold">Routers</h5>
                    <p class="card-text float-right font-weight-bold"><h4>{{ router_count }}0</h4></p>
                    <a href="http://127.0.0.1:8000/assets/list/?product_type=printer"
                       class="btn btn-primary stretched-link">View</a>
                    <div class="icon col-sm-5 mt-5 ml-2">
                        <img src="/media/ICON/assets/277965.png" width="55px">

                    </div>
                </div>
            </div>
        </div>
    <div class="col-sm-3 mt-4 mb-4">
            <div class="card text-white bg-dark">
                <div class="card-body">
                    <h5 class="card-title font-weight-bold">Ext HDD</h5>
                    <p class="card-text float-right font-weight-bold"><h4>{{ ehdd_count }}0</h4></p>
                    <a href="http://127.0.0.1:8000/assets/list/?product_type=printer"
                       class="btn btn-primary stretched-link">View</a>
                    <div class="icon col-sm-5 mt-5 ml-2">
                        <img src="/media/Screenshot%20at%202020-04-16%2010-26-43.png" width="63px">

                    </div>
                </div>
            </div>
        </div>
    </div>


{% endblock %}